* Header                                                             :noexport:
# -*- mode: org; -*-
# (my/execute-startup-blocks)

#+TITLE: My NixOS Config Setup
#+AUTHOR: Curtis D'Alves
#+EMAIL: curtis.dalves@gmail.com
#+DESCRIPTION: My NixOS Configuration File, Written in Org-mode.
#+STARTUP: indent lognoteclock-out
#+OPTIONS: html-postamble:nil toc:nil d:nil num:nil :results nil
#+PROPERTY: header-args :tangle init.el :comments link :results none

* Abstract :ignore:
  :PROPERTIES:
  :CUSTOM_ID: Abstract
  :END:

  This is my literate [[nixos.org/manual/nixos/stable][NixOS]] configuration.

* Table of Contents                                            :Github:TOC_4:
  :PROPERTIES:
  :CUSTOM_ID: Table-of-Contents
  :END:
- [[#abstract][Abstract]]
- [[#installing-nixos][Installing NixOS]]
  - [[#formatting-for-luks-encryption-on-btrfs][Formatting for LUKS Encryption on BTRFS]]
  - [[#generate-config][Generate Config]]
  - [[#install][Install]]
  - [[#post-install][Post-Install]]
- [[#setting-up-your-config-files][Setting Up Your Config Files]]
  - [[#choosing-a-channel][Choosing a Channel]]
  - [[#multi-system-file-layout][Multi-System File Layout]]
  - [[#building-this-document][Building This Document]]
- [[#template][Template]]
- [[#imports][Imports]]
- [[#overlays][Overlays]]
- [[#system-packages][System Packages]]
- [[#boot-loader][Boot loader]]
  - [[#supporting-btrfs-and-ntfs-file-system][Supporting BTRFS and NTFS File System]]
  - [[#disable-ertm][Disable ertm]]
- [[#kernel][Kernel]]
  - [[#kernel-modules][Kernel Modules]]
- [[#virtual-box][Virtual Box]]
- [[#system-settings][System Settings]]
  - [[#timezone][TimeZone]]
  - [[#locale][Locale]]
  - [[#allow-proprietary-software][Allow Proprietary Software]]
  - [[#fonts][Fonts]]
  - [[#keyboard-layout][Keyboard Layout]]
  - [[#swap-control-and-caps][Swap Control and Caps]]
  - [[#global-environment-variables][Global Environment Variables]]
  - [[#systemd][Systemd]]
- [[#cron][Cron]]
- [[#openssh][OpenSSH]]
- [[#networking][Networking]]
  - [[#firewall][Firewall]]
- [[#graphics][Graphics]]
  - [[#nvidia][Nvidia]]
  - [[#nvidia-prime][Nvidia Prime]]
- [[#desktop-environment][Desktop Environment]]
  - [[#gnome-3][Gnome 3]]
  - [[#kde-plasma5][KDE Plasma5]]
  - [[#none--xmonad][None + Xmonad]]
- [[#bluetooth][Bluetooth]]
- [[#sounds-settings][Sounds Settings]]
- [[#touchpad-support][TouchPad support]]
  - [[#xbox-controller-support][Xbox controller support]]
- [[#shell-environment][Shell Environment]]
- [[#users-management][Users Management]]
- [[#open-razer][Open Razer]]
- [[#emacs-daemon][Emacs Daemon]]
- [[#steam][Steam]]
- [[#gamemode][Gamemode]]
- [[#dropbox][Dropbox]]
- [[#noisetorch][NoiseTorch]]
- [[#nixconf][Nix.conf]]
- [[#nix-extra-options][Nix Extra Options]]
- [[#nix-permitted-insecure-packages][Nix Permitted Insecure Packages]]
- [[#system-upgrades][System Upgrades]]
- [[#opt-in-state][Opt-In State]]
  - [[#figuring-out-what-to-persist][Figuring out what to Persist]]
  - [[#persisting-files-removed][Persisting Files #REMOVED]]
    - [[#persisting-machine-id][Persisting Machine-ID]]
  - [[#root-rollback-removed][Root Rollback #REMOVED]]
  - [[#copying-files-to-persist][Copying Files to Persist]]
- [[#home-manager][Home Manager]]
  - [[#shell-configuration][Shell Configuration]]
    - [[#shell-aliases][Shell Aliases]]
  - [[#alacritty][Alacritty]]
  - [[#nix-direnv][Nix-Direnv]]
  - [[#dconf-config-gnome][dconf Config (Gnome)]]
  - [[#xmonad--kde-removed][XMonad + KDE #REMOVED]]
  - [[#xmonad--none-removed][XMonad + None #REMOVED]]
  - [[#picom-removed][Picom #REMOVED]]
  - [[#gtk-theme-removed][GTK Theme #REMOVED]]
  - [[#vs-code][VS Code]]
  - [[#keyboard-layout-1][Keyboard Layout]]
  - [[#rofi-removed][Rofi #REMOVED]]
  - [[#polybar-removed][Polybar #REMOVED]]
  - [[#dunst-removed][Dunst #REMOVED]]

* Installing NixOS 
The installation part of the [[https://nixos.org/manual/nixos/stable/index.html#ch-installation][NixOS Manual]] describes how to perform a standard
installation better than I can

** Formatting for LUKS Encryption on BTRFS
There's a pretty good [[https://mt-caret.github.io/blog/posts/2020-06-29-optin-state.html][blog post on Encrypted BTRFS Root with Opt-in State in
NixOS]] covering how to do this. 

- First partition an EFI partition, swap and root
  partition (where ~/dev/sda~ is the disk you've chosen to install on, you can
  check your disks with ~fdisk -l~)
  #+BEGIN_SRC shell :tangle no
  parted /dev/sda -- mklabel gpt
    # make root
  parted /dev/sda -- mkpart primary 512MiB -8GiB
    # make swap
  parted /dev/sda -- mkpart primary linux-swap -8GiB 100%
    # make boot
  parted /dev/sda -- mkpart ESP fat32 1MiB 512MiB
  parted /dev/sda -- set 3 esp on
  #+END_SRC
- Then encrypt the root partition (~/dev/sda1~ in this example)  with [[https://wiki.archlinux.org/index.php/Dm-crypt][dm-crypt]]
  #+BEGIN_SRC shell :tangle no
  cryptsetup --verify-passphrase -v luksFormat /dev/sda1
  cryptestup open /dev/sda1 enc
  #+END_SRC
- Then format each partition (assuming ~/dev/sda2~ is swap and ~/dev/sda3~ is boot)
  #+BEGIN_SRC shell :tangle no
  mkfs.vfat -n boot /dev/sda3 
  mkswap /dev/sda2
  swapon /dev/sda2
  mkfs.btrfs /dev/mapper/enc
  #+END_SRC
- Next, create the btrfs subvolumes. You can play around with this, this example
  creates a persist subvolume and makes blank snapshot of root to do *Opt-In
  State* (see the section [[#opt-in-state][Opt-In State]])
  #+BEGIN_SRC shell :tangle no
  mount -t btrfs /dev/mapper/enc /mnt

  btrfs subvolume create /mnt/root
  btrfs subvolume create /mnt/home
  btrfs subvolume create /mnt/nix
  btrfs subvolume create /mnt/persist
  btrfs subvolume create /mnt/log

  # We then take an empty *readonly* snapshot of the root subvolume,
  # which we'll eventually rollback to on every boot.
  btrfs subvolume snapshot -r /mnt/root /mnt/root-blank

  umount /mnt
  #+END_SRC
- Now we need to mount all our subvolumes so that a proper fstab gets generated
  for when we finally run ~nixos-build~
  #+BEGIN_SRC shell :tangle no
  mount -o subvol=root,compress=zstd,noatime /dev/mapper/enc /mnt

  mkdir /mnt/home
  mount -o subvol=home,compress=zstd,noatime /dev/mapper/enc /mnt/home

  mkdir /mnt/nix
  mount -o subvol=nix,compress=zstd,noatime /dev/mapper/enc /mnt/nix

  mkdir /mnt/persist
  mount -o subvol=persist,compress=zstd,noatime /dev/mapper/enc /mnt/persist

  mkdir -p /mnt/var/log
  mount -o subvol=log,compress=zstd,noatime /dev/mapper/enc /mnt/var/log
  #+END_SRC
- Also don't forget to mount your boot partition (assuming ~/dev/sda3~ is boot
  partition)
  #+BEGIN_SRC shell :tangle no
  mkdir /mnt/boot
  mount /dev/sda3 /mnt/boot
  #+END_SRC
  
** Generate Config
After you're done partitioning, formatting and everything is mounted (with root
at ~/mnt~ of course)
- Generate a default nixos configuration file int ~/mnt/etc/nixos~ with
  #+BEGIN_SRC shell :tangle no
  nixos-generate-config --root /mnt
  #+END_SRC
- Then edit ~/mnt/etc/nixos/configuration~ to configure your system, I recommend
  starting with a minimalist install until you can actually boot into your
  system
- The [[https://nixos.org/manual/nixos/stable/index.html#ch-installation][NixOS Manual]] gives a good overview of the essentials you should configure,
  but here's a good sample inital configuration for an EFI system with a btrfs root
  #+BEGIN_SRC nix :tangle no
  { config, pkgs, ... }:

  {
    imports =
      [ # Include the results of the hardware scan.
        ./hardware-configuration.nix
      ];

    boot.supportedFilesystems = [ "btrfs" ];
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = true;

    hardware.enableAllFirmware = true;
    nixpkgs.config.allowUnfree = true;

    networking.hostName = "NixBoot"; # Define your hostname.
    networking.networkmanager.enable = true;

    time.timeZone = "America/Toronto";

    networking.useDHCP = false;
    networking.interfaces.enp0s31f6.useDHCP = true; # this should be generated for you
    networking.interfaces.wlp82s0.useDHCP = true;   # need to manually turn on any network interfaces

    i18n.defaultLocale = "en_US.UTF-8";
    console = {
      font = "sun12x22";
      keyMap = "us";
    };

    services.xserver.enable = true;
    services.xserver.displayManager.sddm.enable = true;
    services.xserver.desktopManager.plasma5.enable = true;

    sound.enable = true;
    hardware.pulseaudio.enable = true;

    services.xserver.libinput.enable = true;

    users.users.dalvescb = {
      isNormalUser = true;
      extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    };

    environment.systemPackages = with pkgs; [
      wget 
      vim
      emacs
      chromium
      git
    ];
  
    services.openssh.enable = true;
    system.stateVersion = "20.09"; # Did you read the comment?

    }
    #+END_SRC
  - Also make sure everything in ~/mnt/etc/nixos/hardware-configuration.nix~ is
    correct, in particular if you followed the btrfs file layout in the previous
    section make sure ~/var/log~ subvolume is mounted early enough in the boot
    process by adding ~neededForBoot = true~, i.e.
    #+BEGIN_SRC nix :tangle no
    fileSystems."/var/log" =
      { device = "/dev/disk/by-uuid/f73c53b7-ae6c-4240-89c3-511ad918edcc";
        fsType = "btrfs";
        options = [ "subvol=log" "compress=zstd" "noatime" ];
        neededForBoot = true;
      };
  #+END_SRC
  
** Install
Finally, after you've you have generated and edited your configuration, simply
run
#+BEGIN_SRC shell :tangle no
nixos-install
reboot
#+END_SRC

** Post-Install
After a successful installation you should 
- begin properly configuring ~/mnt/etc/nixos/configuration~
- if you followed the btrfs subvolume setup in [[#formatting-for-luks-encryption-on-btrfs][Formatting for LUKS Encryption on
  BTRFS]] optionally enable [[#opt-in-state][Opt-In State]]
  
* Setting Up Your Config Files
[[#building-this-document][Building This Document]] will generate a file ~common-configuration.nix~, which is
designed to be imported by your main ~configuration.nix~ that will contain any
system specific information so that the majority of your config can be shared by
multiple systems 

** Choosing a Channel
NixOS will default to the most recent stable channel (at the time of writing
this 20.09). To list the current channel you're on
#+BEGIN_SRC shell :tangle no
sudo nix-channel --list
  nixos https://nixos.org/channels/nixos-20.09
#+END_SRC
I use the nixos-unstable channel (it's not really that unstable, and makes NixOS
more of a rolling-release distro like Arch). Switch channels with
#+BEGIN_SRC shell :tangle no
sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixos
sudo nix-channel --update
#+END_SRC
and then rebuild and upgrade (you should upgrade every time you do a nix-channel update)
#+BEGIN_SRC shell :tangle no
sudo nixos-rebuild switch --upgrade
#+END_SRC

** Multi-System File Layout
- Clone this repository to your home, i.e. if ~<user>~ is your username:
  ~/home/<user>/nixconfig~
- Create a new directory in the repo to store system specific configuration
  files, i.e. if <hostname> is your hostname create the directory:
  ~/home/<user>/nixconfig/<hostname>~
- Copy your generated ~/etc/nixos/hardware-configuration.nix~ into
  ~/home/<user>/nixconfig/<hostname>~
- Create a main configuration file
  ~/home/<user>/nixconfig/<hostname>/configuration.nix~ which will import the
  other configurations and contain any system specific config, for example:
  #+BEGIN_SRC nix :tangle no

  {
    imports =
      [ 
        ./hardware-configuration.nix
        ../common-configuration.nix
        ./user-configuration.nix
      ];

    networking.hostName = "<hostname>"; # replace with actual hostname
    nix.nixPath = [
      "home-manager=/nix/var/nix/profiles/per-user/root/channels/home-manager"
      "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs"
      "nixos-config=/home/<user>/nixconfig/${config.networking.hostName}/configuration.nix"
    ];


    networking.useDHCP = false;
    networking.interfaces.<interface>.useDHCP = true; # replace wiht actual networking interfaces

    fileSystems."/var/log".neededForBoot = true;
  }
  #+END_SRC
- Create a ~/home/<user>/nixconfig/<hostname>/user-configuration.nix~ and setup
  your user configuration (see [[#users-management][Users Management]])

- ~nix.nixPath~ will change your default ~nixo-config~ path from ~/etc/nixos~,
  but the first time you rebuild you'll have to specify this manually, i.e.
  #+BEGIN_SRC shell :tangle no
  nixos-rebuild -I /home/<user>/nixconfig/<hostname>/configuration.nix switch
  #+END_SRC
  
** Building This Document
This is an Emacs [[https://orgmode.org][Org Mode]] document, and thus needs emacs to be
built. However, on a fresh NixOS installation you can build this from a
temporary shell environment via
#+BEGIN_SRC sh :tangle no :results output silent 
nix-shell -p emacs
emacs --file NixOSConfiguration.org --eval '(progn (org-babel-tangle) (kill-emacs))'
#+END_SRC
However, I recommend you first do a basic install as laid out in [[#installing-nixos][Installing
NixOS]], then using ~org-babel-tangle~ from within emacs.

* Template
  - The NixOS configuration file is actually a /Nix expression/, which is the Nix
    package manager's purely functional language for describing how to build
    packages.
  - The first line (~{ config, pkgs, ... }~) denotes that  this is actually a
    function that takes at least two arguments ~config~ and ~pkgs~. The function
    returns a set of *option definitions* ~{ <<insert-config-here>> }~ (i.e. where
    the entirety of the configuration code in this document is inserted)
    
    #+BEGIN_SRC nix :tangle common-configuration.nix :noweb yes
    # Edit this configuration file to include configuration common between hosts
    # NOTE this was generated from the org file NixOSConfiguration.org
    { config, pkgs, ... }:

    {
      <<insert-config-here>>
    }
    #+END_SRC
    
* Imports
Import other modules (and [[https://nix-community.github.io/home-manager/index.html#sec-install-nixos-module][Home Manager]]) here
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
imports = [ <home-manager/nixos> ];
#+END_SRC
*NOTE* to import home-manager this way you need to add it to nix channels with
#+BEGIN_SRC shell :tangle no
sudo nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
sudo nix-channel --update
#+END_SRC
Also make sure home-manager is in your ~NIX_PATH~ variable (see [[#multi-system-file-layout][Multi-System
File Layout]] for an example of how/where to set it)

* Overlays
Overlays provide a method to extend and change the imported nixpkgs. See
[[https://nixos.wiki/wiki/Overlays][Overlays]] for details

#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
nixpkgs.overlays = let
  # this overlay is just a tmp fix for a steam update issue, track here https://github.com/ValveSoftware/steam-runtime/issues/462
  # remove me when the issue is fixed
  steam-overlay =(self: super: { steam = super.steam.override { extraPkgs = pkgs: with pkgs; [ pango harfbuzz libthai ]; }; } ) ;
  plasma-framework-overly = (final: prev:
    let
      libsForQt5 = prev.libsForQt5.overrideScope' (
        finalx: prevx:
        let
          kdeFrameworks = prevx.kdeFrameworks.overrideScope' (
            finaly: prevy: {
              plasma-framework = prevy.plasma-framework.overrideAttrs (oldAttrs:
                rec {
                  # NOTE update me as nixpkgs gets updated, see
                  # nixpkgs/pkgs/development/libraries/kde-frameworks/srcs.nix to see current version
                  # and apply fixes in https://github.com/xmonad/xmonad/issues/174
                  src = pkgs.fetchurl {
                    url = "https://github.com/dalvescb/plasma-framework/archive/refs/tags/xmonad-5.90.tar.gz";
                    sha256 = "sha256-8EoNNnSW6nxwyc5h/vR6BnF71c3J2WlZL1ivHfcGsWI=";
                    name = "plasma-framework-5.90.0.tar.gz";
                  };
                });
            });
          plasma5 = prevx.plasma5;
          kdeGear = prevx.kdeGear;
          all = kdeFrameworks // plasma5 // plasma5.thirdParty // kdeGear;
          libsForQt5 = all // {
            inherit kdeFrameworks plasma5 kdeGear;
            kdeApplications = kdeGear;
          };
        in libsForQt5 // {
          inherit libsForQt5;
        });
    in { inherit libsForQt5;
          inherit (libsForQt5) plasma-desktop;
          plasma5Packages = libsForQt5;
        }
  );
  hls-overlay = (self: super:
    let
      disableCabalFlag = super.haskell.lib.disableCabalFlag;

      hslWithoutPlugins = super.haskellPackages.haskell-language-server.override  {
        hls-fourmolu-plugin = null;
        hls-ormolu-plugin = null;
        # supportedGhcVersions = [ "884" "8107" "90" ];
      };
      withoutFourmoluFlag = disableCabalFlag hslWithoutPlugins "fourmolu";
      hls = disableCabalFlag withoutFourmoluFlag "ormolu";
    in { haskell-language-server = hls;  } );
# in [ plasma-framework-overly ];
in [ ];  # use no overlays atm
#+END_SRC

* System Packages
Install packages system-wide by adding them to ~environment.systemPackages~.
*NOTE* multiple declarations (between modules) will result in /merging/ of this
list, so not necessarily all installed system packages need to be located here
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
environment.systemPackages = with pkgs; [
  wget
  ispell
  vim
  emacs
  git
  imagemagick
  subversion
  firefox-bin
  chromium
  brave
  discord
  nix-index
  libva
  libva-utils
  razergenie
  linuxPackages_5_15.openrazer
  pciutils
  arc-kde-theme
  # plasma5.kwallet-pam
  # plasma5.sddm-kcm
  haskellPackages.stack
  (haskell-language-server.override { supportedGhcVersions = [ "902" "924" ]; })
  # haskell-language-server
  haskellPackages.Agda
  haskellPackages.implicit-hie
  cabal-install
  ghc
  python3Full
  snapper
  python38Packages.setuptools
  # emacs26Packages.agda2-mode
  agda
  agda-pkg
  texlive.combined.scheme-full
  # alacritty
  libsForQt5.ark
  zip
  unzip
  unrar
  mattermost-desktop
  slack
  teams
  zoom-us
  snapper
  # steam
  # steam-run
  chntpw
  ntfs3g
  libsForQt5.plasma-integration
  libsForQt5.plasma-browser-integration
  # libsForQt5.kdeconnect-kde
  libsForQt5.okular
  xorg.xkill
  htop
  linuxPackages_5_15.xpadneo
  gsmartcontrol
  smartmontools
  pkg-config
  alsa-lib
  xorg.xrandr
  arandr
  killall
  libnotify
  jupyter
  pandoc
  libreoffice
  rnnoise-plugin
  noisetorch
  vulkan-tools
  vulkan-loader
  vulkan-validation-layers
  python311Packages.pygments
  ipopt
  docker
  # haskell.packages.ghc883.haskell-language-server
  glmark2
  ripgrep
  ripgrep-all
  # dropbox - we don't need this in the environment. systemd unit pulls it in
  dropbox-cli
  nodePackages.mermaid-cli
  graphviz
  xdot
  haskellPackages.graphmod
  obs-studio
  vlc
  haruna
  mkvtoolnix
  niv
  shotcut
  gnome.nautilus
  gnome.sushi
  scrot
  btop
  lm_sensors
  xsensors
  hddtemp
  kde-gtk-config
  arc-theme
  materia-theme
  orchis-theme
  libsForQt5.knotifications
  libsForQt5.sddm-kcm
  libsForQt5.konqueror
  rnix-lsp
  spotify
  webtorrent_desktop
  transmission-qt
  kgraphviewer
  libgtop
  etcher
  openrgb
  poppler
  ditaa
  texlab
  ltex-ls
  html-tidy
  dolphin-emu
  gnome-icon-theme
  gnome.gnome-tweaks
  gnome.dconf-editor
  gnomeExtensions.appindicator
  gnomeExtensions.just-perfection
  gnomeExtensions.gsconnect
  gnomeExtensions.another-window-session-manager
  gnomeExtensions.vitals
  # gnomeExtensions.freon
  gnomeExtensions.dash-to-panel
  gnomeExtensions.sound-output-device-chooser
  gnomeExtensions.gtk-title-bar
];
#+END_SRC

* Boot loader
 Configure the GRUB 2 bootloader on UEFI with
 #+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
 # Use the GRUB 2 boot loader (with EFI support)
 boot.loader.grub.enable = true;
 boot.loader.grub.version = 2;
 boot.loader.grub.device = "nodev";
 boot.loader.grub.efiSupport = true;
 boot.loader.grub.useOSProber = true;
 boot.loader.grub.fsIdentifier = "label";
 boot.loader.grub.efiInstallAsRemovable = true;
 boot.loader.efi.efiSysMountPoint = "/boot";

 # Use the systemd-boot EFI boot loader.
 # boot.loader.systemd-boot.enable = true;
 # boot.loader.efi.canTouchEfiVariables = true;
 #+END_SRC

** Supporting BTRFS and NTFS File System
If using a BTRFS filesystem add it to ~boot.supportedFilesystems~ and enable
~boot.hardware.enableAllFirmware~
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
boot.supportedFilesystems = [ "btrfs" "ntfs" ];
hardware.enableAllFirmware = true;
#+END_SRC

** Disable ertm
For some reason .. you need to disable ertm to bluetooth pair a xbox controller
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
boot.extraModprobeConfig = '' options bluetooth disable_ertm=1 '';
#+END_SRC

* Kernel
See [[https://nixos.wiki/wiki/Linux_kernel][NixOS Wiki Linux Kernel]] for details on selecting a kernel. If you don't
specify a kernel, it'll default to a the "latest" lts kernel
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
boot.kernelPackages = pkgs.linuxPackages_5_15;
#+END_SRC
** Kernel Modules
Set kernel modules to be loaded here

* Virtual Box
If installing NixOS inside of a virtual box (which is a great way to develop a
config) make sure to enable Guest Additions to get some nice extra features
including much better video support (add this to your hosts ~configuration.nix~)
  #+BEGIN_SRC nix :tangle no 
  virtualisation.virtualbox.guest.enable = true;
  #+END_SRC

* System Settings
** TimeZone
See [[https://en.wikipedia.org/wiki/List_of_tz_database_time_zones][list of tz database time zones]] for possible options
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
time.timeZone = "America/Toronto";
#+END_SRC

** Locale
Use the command ~locale -a~ to see a list of valid locales
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
i18n.defaultLocale = "en_US.UTF-8";
console = {
  font = pkgs.lib.mkForce "sun12x22";
  keyMap = pkgs.lib.mkForce "us";
};
#+END_SRC

** Allow Proprietary Software
Because NixOS is high and mighty Open Source software you need to manually specify
the installation of propriety (unfree) software is allowed (see the
[[https://nixos.wiki/wiki/FAQ/How_can_I_install_a_proprietary_or_unfree_package%3F][NixOS Wiki on Proprietary Packages]])
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
nixpkgs.config.allowUnfree = true;
#+END_SRC

** Fonts
Install fonts by adding them to ~fonts.fonts.pkgs~ (use override to select fonts
from a big package) see [[https://nixos.wiki/wiki/Fonts][NixOS Wiki Fonts]] for details
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
fonts = {
  fonts = with pkgs; [
      dejavu_fonts
      (nerdfonts.override { fonts = [ "DejaVuSansMono" ]; } )
      source-code-pro
      emacs-all-the-icons-fonts
      jetbrains-mono
      font-awesome
      hack-font
      inconsolata
      inconsolata-nerdfont
    ];
};
#+END_SRC

** Keyboard Layout
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.xserver.layout = "us";
#+END_SRC
** Swap Control and Caps
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.xserver.xkbOptions = "ctrl:swapcaps"; # this stopped working on home-manager update. needs to be set through home.keyboard.options now?
#+END_SRC
** Global Environment Variables
Set global environment variables (to be initialized in /etc/profile) here
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
environment.variables =
  {
    # In firefox in about:config I switched gfx.webrender.all to true to fix bug causing
    # lag under high gpu load. 
    # But this introduced a new bug! that is fixed by this environment variable
    MOZ_X11_EGL = "1";
    HOSTNAME = "${config.networking.hostName}";
    XDG_SESSION_TYPE="x11";
    # needed to fix bug https://github.com/NixOS/nixpkgs/issues/48424
    WEBKIT_DISABLE_COMPOSITING_MODE = "1";
  };
#+END_SRC
** Systemd 
Set an extra variables usually set in ~/etc/systemd/system.conf~ here
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
systemd.extraConfig = ''
                    DefaultTimeoutStopSec=5s
                    DefaultTimeoutStartSec=5s
                    '';
#+END_SRC

* Cron
See [[https://nixos.wiki/wiki/Cron]] for details on configuring NixOS for cron
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.cron = {
  enable = true;
  systemCronJobs = [
      # updates ip for duckdns
      "*/5 * * * * root /home/dalvescb/duckdns/duck.sh >/dev/null 2>&1"
    ];
};
#+END_SRC

* OpenSSH
Enable OpenSSH server here. NOTE you can authorize public keys for users by adding
~users.users.USERNAME.openssh.authroizedKeys.keys = [ "PUBLIC KEY STRING" ];~ to
host specific configuration file
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.openssh.enable = true;
#+END_SRC

* Networking
- The hostname and DHCP settings should already be set in your
  ~configuration.nix~ (see [[#multi-system-file-layout][Multi-System File Layout]])
- Enable network manager with
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
networking.networkmanager.enable = true;
#+END_SRC

** Firewall
Open TCP/UDP ports on which incoming connects are accepted:
  - *KDE Connect* ports: 1714-1764
  - *Dropbox* ports: 17500
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
networking.firewall.allowedTCPPortRanges = [
  # KDE Connect
  {
    from = 1714;
    to = 1764;
  }
  # Dropbox
  {
    from = 17500;
    to = 17500;
  }
  # SSH
  {
    from = 22;
    to = 22;
  } 
];

networking.firewall.allowedUDPPortRanges = [
  # KDE Connect
  {
    from = 1714;
    to = 1764;
  }
  # Dropbox
  {
    from = 17500;
    to = 17500;
  }
  # SSH
  {
    from = 22;
    to = 22;
  }
];
#+END_SRC

* Graphics
Because graphics drivers vary from system to system, I put the configuration for
them in their own modules (separate from the ~common-configuration.nix~ file the
rest of this document generates. The two main configurations I have are
- ~nvidia.nix~ standard proprietary nvidia driver that uses just a discrete gpu
- ~nvidiaprime.nix~
** Nvidia
A simple setup for a dedicated nvidia MXM card can be done via the following
configuration
#+BEGIN_SRC nix :tangle nvidia.nix
{pkgs, ... }:

{
  services.xserver.videoDrivers = [ "nvidia" ];
  # services.xserver.dpi = 96;
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
        vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
      ];
    setLdLibraryPath = true;
    driSupport = true;
    driSupport32Bit = true;
  };
}
#+END_SRC

** Nvidia Prime
For a laptop with dedicated and integrated graphics, you can operate in hybrid
mode (to get the power of the dedicated gpu when necessary and power saving with
integrated) using Nvidia Optimus via the following configuration
#+BEGIN_SRC nix :tangle nvidiaprime.nix
{pkgs, ... }:

{
  # environment.systemPackages = [ nvidia-offload ]; 
  # services.xserver.videoDrivers = [ "intel" "modesetting" "nvidia" ];
  services.xserver.videoDrivers = [ "nvidia" ];
  services.xserver.dpi = 96;
  hardware.nvidia.prime = {
    # offload.enable = true;
    sync.enable = true;
    # Bus ID of the Intel GPU. You can find it using lspci, either under 3D or VGA
    intelBusId = "PCI:0:2:0";

    # Bus ID of the NVIDIA GPU. You can find it using lspci, either under 3D or VGA
    nvidiaBusId = "PCI:1:0:0";
  };
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
        vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
      ];
  };
  hardware.opengl.driSupport32Bit = true;
}
#+END_SRC
*NOTE* it requires ~nixpkgs.config.allowUnfree~ enabled (see [[#allow-proprietary-software][Allow Proprietary Software]])

* Desktop Environment
** Gnome 3
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.xserver.enable = true;
services.xserver.displayManager.gdm.enable = true;
services.xserver.desktopManager.gnome.enable = true;

services.dbus.packages = [ pkgs.dconf ];
services.udev.packages = with pkgs; [ gnome.gnome-settings-daemon ];
#+END_SRC

** KDE Plasma5
#+BEGIN_SRC nix :tangle no
services.xserver.enable = true;
# services.xserver.displayManager.lightdm.enable = true;
services.xserver.displayManager.sddm.enable = true;
services.xserver.desktopManager.plasma5.enable = true;

# services.xserver.displayManager.defaultSession = "none+xmonad";
services.xserver.windowManager.xmonad = {
    enable = true;
    enableContribAndExtras = true;
  };
#+END_SRC

Global Theme doesn't seem to work (for downloading/installing new themes) but
- You can download new themes from the [[https://store.kde.org][KDE Store]] (say ~Sweet.tar.xz~) and
  install them (mutably) with
  #+BEGIN_SRC shell :tangle no
  kpackagetool5 -t Plasma/LookAndFeel -i Sweet.tar.xz
  #+END_SRC
- This installs the theme in ~$HOME/.local/share/plasma/look-and-feel~
- To switch the theme on, either edit ~$HOME/.config/plasmarc~ manually or do so
  with 
  #+BEGIN_SRC shell :tangle no
  kwriteconfig5 --key Theme Sweet
  #+END_SRC

** None + Xmonad
#+BEGIN_SRC nix :tangle no 
services = {
  gnome.gnome-keyring.enable = true;
  gnome.sushi.enable = true;
  upower.enable = true;
  
  dbus = {
    enable = true;
    packages = [ pkgs.gnome.dconf ];
  };

  xserver.enable = true;

  xserver.displayManager.defaultSession = "none+xmonad";

  xserver.windowManager.xmonad = {
    enable = true;
    enableContribAndExtras = true;
  };
};

console.useXkbConfig = true;
systemd.services.upower.enable = true;
#+END_SRC

* Bluetooth
Enable bluetooth support with one simple line (see
[[https://nixos.wiki/wiki/Bluetooth][NixOS Wiki Bluetooth]] for further details)
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
hardware.bluetooth.enable = true;
services.blueman.enable = true;
hardware.bluetooth.settings = {
  General = {
    Enable = "Source,Sink,Media,Socket";
    };
};
#+END_SRC
The ~hardware.bluetooth.settings~ was suggested for enabling the A2DP profile
for headsets in the wiki, although it might not be necessary

* Sounds Settings
Standard sound support is enabled through [[https://nixos.wiki/wiki/PulseAudio][Pulse Audio]].

However, I have switched to [[https://nixos.wiki/wiki/PipeWire][Pipewire]] as it seems to be less buggy with bluetooth
headsets. I've left my previous pulse audio configuration commented out
 #+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
 sound.enable = true;
 # hardware.pulseaudio = {
 #    enable = true;
 #    support32Bit = true;
 #    # NixOS allows either a lightweight build (default) or full build of PulseAudio to be installed.
 #    # Only the full build has Bluetooth support, so it must be selected here.
 #    package = pkgs.pulseaudioFull;
 # };
 hardware.pulseaudio.enable = false;
 security.rtkit.enable = true;
 services.pipewire = {
  enable = true;
  alsa.enable = true;
  alsa.support32Bit = true;
  pulse.enable = true;
  # If you want to use JACK applications, uncomment this
  #jack.enable = true;
 };
 #+END_SRC
 You may also need to add users to the ~audio~ group (see [[#users-management][Users Management]])

* TouchPad support
To enable touchpad support through [[https://wiki.archlinux.org/index.php/Libinput][LibInput]] add
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.xserver.libinput.enable = true;
#+END_SRC

** Xbox controller support
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
hardware.xpadneo.enable = true;
#+END_SRC

* Shell Environment
Enable the default shell (i.e. bash,zhs,fish,etc) here
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
programs.zsh.enable = true;
programs.fish.enable = true;
#+END_SRC
To set the default shell see the next section ([[#users-management][Users Management]])

* Users Management
I like to declaretively set my user configurations, including their password via
a ~hashedPassword~. Because of this, I keep my user configuration in a seperate
file ~user-configuration.nix~ that I import and do not include in this document
or GitHub repo.

An example of this file is
#+BEGIN_SRC nix :tangle no 
{ config, pkgs, ... }:

{
  users.mutableUsers = false;

  users.users.dalvescb = {
    isNormalUser = true;
    home = "/home/dalvescb";
    extraGroups = [ "wheel" "networkmanager" ]; 
    shell = pkgs.zsh;
    hashedPassword = "asdl;fkjasdfnamsdcoimalkamxzcOIUZlknasdfkdf";
          # generate me with mkpasswd -m sha-512
  };

  # disable root password
  users.users.root.hashedPassword = "*";
}
#+END_SRC

* Open Razer
In order to use *razergenie* (installed in [[#system-packages][System Packages]]) to configure rgb for
razer peripherals, you need to enable the open razer daemon with
#+BEGIN_SRC nixos :tangle no :noweb-ref insert-config-here
hardware.openrazer.enable = true;
#+END_SRC
You also need to add your user to the ~plugdev~ group in your user configuration
(see  [[#users-management][Users Management]])

* Emacs Daemon
To install and enable the systemd user service for the Emacs daemon, add the
following
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
services.emacs.enable = true;
services.emacs.defaultEditor = true;
#+END_SRC

* Steam
To fix an issue with proton 5.13, steam now needs to be installed as a service
(for the foreseeable future?), and not in ~environment.system-packages~. See the
following [[https://github.com/NixOS/nixpkgs/pull/114024][pull request]] for details
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
programs.steam.enable = true;
#+END_SRC

* Gamemode
Gamemode is a daemon/lib for linux that allows games to request a set of
optimizations to be temporarily applied. Will generally be used with steam by
adding the launch option ~gamemoderun %command$~
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
programs.gamemode.enable = true;
#+END_SRC

* Dropbox
Unfortunately there's no Dropbox module in nixpkgs, however the [[https://nixos.wiki/wiki/Dropbox][NixOS
Wiki on Dropbox]] provides instructions for adding support via a service like so
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
systemd.user.services.dropbox = {
    description = "Dropbox";
    wantedBy = [ "graphical-session.target" ];
    environment = {
      QT_PLUGIN_PATH = "/run/current-system/sw/" + pkgs.qt5.qtbase.qtPluginPrefix;
      QML2_IMPORT_PATH = "/run/current-system/sw/" + pkgs.qt5.qtbase.qtQmlPrefix;
    };
    serviceConfig = {
      ExecStart = "${pkgs.dropbox.out}/bin/dropbox";
      ExecReload = "${pkgs.coreutils.out}/bin/kill -HUP $MAINPID";
      KillMode = "control-group"; # upstream recommends process
      Restart = "on-failure";
      PrivateTmp = true;
      ProtectSystem = "full";
      Nice = 10;
    };
  };
#+END_SRC

* NoiseTorch
[[https://github.com/lawl/NoiseTorch][NoiseTorch]] is a real-time noise suppressor for Linux that works with PulseAudio
or Pipewire (it requires the setcap wrapper to run properly and thus needs to be
enabled as a service)
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
programs.noisetorch.enable = true;
#+END_SRC

* Nix.conf
These settings will configure settings int ~/etc/nix/nix.conf~

#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
nix.settings.trusted-public-keys = [
  "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" # Binary Cache for Haskell.nix
];

nix.settings.substituters = [
  "https://cache.iog.io" # Binary Cache for Haskell.nix
];

#  this was added to fix the following error when using buildStackProject
# error: derivation '/nix/store/5sdvfa4fg9rsrqnl120ji9gnn6fa15gc-Coconut-env.drv' has '__noChroot' set, but that's not allowed when 'sandbox' is 'true'
nix.settings.sandbox = false;
#+END_SRC

* Nix Extra Options
The following extra options are needed by Home Manager for nix-direnv (see the
[[https://github.com/nix-community/nix-direnv][direnv github]] for details
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
nix.extraOptions = ''
                 keep-outputs = true
                 keep-derivations = true
                 '';
#+END_SRC
* Nix Permitted Insecure Packages
Add any packages marked as insecure that you want to build here anyways
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
nixpkgs.config.permittedInsecurePackages = [
                "electron-12.2.3"
              ];
#+END_SRC
* System Upgrades
Configure how System Upgrades are performed here
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
# enables auto-updating
system.autoUpgrade.enable = false;
system.autoUpgrade.allowReboot = false;

# This value determines the NixOS release from which the default
# settings for stateful data, like file locations and database versions
# on your system were taken. It‘s perfectly fine and recommended to leave
# this value at the release version of the first install of this system.
# Before changing this value read the documentation for this option
# (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
system.stateVersion = "20.09"; # Did you read the comment?
#+END_SRC

* Opt-In State
If you followed the formatting laid out in [[#formatting-for-luks-encryption-on-btrfs][Formatting for LUKS Encryption on
BTRFS]],
(i.e. you should have a BTRFS filesystem with the following subvolumes)
 - root ~/~
 - home ~/home~
 - nix ~/nix~
 - persist ~/persist~
 - log ~/var/log~
then it's possible to setup the root subvolume to restore to a snapshot
automatically each boot. This gives you a nice "clean OS smell" each time you
boot. The article [[https://mt-caret.github.io/blog/posts/2020-06-29-optin-state.html][Encypted Btrfs Root with Opt-in State on NixOS]] gives a good
overview of how to go about this.

Of course this comes at a cost, mainly sometimes you'll want certain files to
persist which will require extra work copying and symlinking to the ~persist~
subvolume

** Figuring out what to Persist
To figure out which files you may want to persist, you'll probably want to take a
diff of files that have changes from your current (in use) root partition and
the blank snapshot. To do this:
- First mount the root subvolume with
  #+BEGIN_SRC sh :tangle no
  sudo mkdir /mnt
  sudo mount -o subvol=/ /dev/mapper/enc /mnt
  ./fs-diff.sh
  #+END_SRC
- Then execute the following script
  #+BEGIN_SRC sh :tangle no
  #!/usr/bin/env bash
  # fs-diff.sh
  set -euo pipefail

  OLD_TRANSID=$(sudo btrfs subvolume find-new /mnt/root-blank 9999999)
  OLD_TRANSID=${OLD_TRANSID#transid marker was }

  sudo btrfs subvolume find-new "/mnt/root" "$OLD_TRANSID" |
  sed '$d' |
  cut -f17- -d' ' |
  sort |
  uniq |
  while read path; do
    path="/$path"
    if [ -L "$path" ]; then
      : # The path is a symbolic link, so is probably handled by NixOS already
    elif [ -d "$path" ]; then
      : # The path is a directory, ignore
    else
      echo "$path"
    fi
  done
  #+END_SRC

** Persisting Files #REMOVED
We copy files/directories in ~/etc/~ to their own spot in ~/persist/etc/~ to
make them persist (~/etc/nixos~ is a good example of a directory we need to do
this with) and use systemd's [[https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html][tmpfiles.d]] to symlink files as necessary 
#+BEGIN_SRC nix :tangle no
environment.etc = {
  # persist /etc/nixos
  nixos.source = "/persist/etc/nixos";
  NIXOS.source = "/persist/etc/NIXOS";
  # persist NetworkManager 
  "NetworkManager/system-connections".source = "/persist/etc/NetworkManager/system-connections";
  # persist adjtime
  # adjtime.source = "/persist/etc/adjtime";
};

systemd.tmpfiles.rules = [
 "L /var/lib/NetworkManager/secret_key - - - - /persist/var/lib/NetworkManager/secret_key"
 "L /var/lib/NetworkManager/seen-bssids - - - - /persist/var/lib/NetworkManager/seen-bssids"
 "L /var/lib/NetworkManager/timestamps - - - - /persist/var/lib/NetworkManager/timestamps"
 "L /var/lib/bluetooth - - - - /persist/var/lib/bluetooth"
];

security.sudo.extraConfig = ''
  # rollback results in sudo lectures after each reboot
  Defaults lecture = never
'';
#+END_SRC

*NOTE* the first time you add something to ~/persist~ you still need to manually
 copy them (see [[#copying-files-to-persist][Copying Files to Persist]])

*** Persisting Machine-ID
- The file ~/etc/machine-id~ is blank on first boot but then is given a unique
  value corresponding to your machine-id. We need to persist this for certain
  functionality (including persisting ~journald~ entries).
- *AFTER FIRST BOOT* add the following to your hosts ~configuration.nix~
  #+BEGIN_SRC nix :tangle no
  environment.etc."machine-id".text = "b7665d1914cd41dc93406d8488004eb0";
  #+END_SRC
- *WHERE* the above code is the generated machine-id inside ~/etc/machine-id~
  after first boot
- *NOTE* because this is unique to different hosts this isn't generated by this
  document in ~common-configuration.nix~, it must be added to
  ~configuration.nix~ manually
  
** Root Rollback #REMOVED
Finally, we need to configure NixOS to rollback the root subvolume (to our
root-blank snapshot) on boot
#+BEGIN_SRC nix :tangle no
# Note `lib.mkBefore` is used instead of `lib.mkAfter` here.
boot.initrd.postDeviceCommands = pkgs.lib.mkBefore ''
  mkdir -p /mnt

  # We first mount the btrfs root to /mnt
  # so we can manipulate btrfs subvolumes.
  mount -o subvol=/ /dev/mapper/enc /mnt

  # While we're tempted to just delete /root and create
  # a new snapshot from /root-blank, /root is already
  # populated at this point with a number of subvolumes,
  # which makes `btrfs subvolume delete` fail.
  # So, we remove them first.
  #
  # /root contains subvolumes:
  # - /root/var/lib/portables
  # - /root/var/lib/machines
  #
  # I suspect these are related to systemd-nspawn, but
  # since I don't use it I'm not 100% sure.
  # Anyhow, deleting these subvolumes hasn't resulted
  # in any issues so far, except for fairly
  # benign-looking errors from systemd-tmpfiles.
  btrfs subvolume list -o /mnt/root |
  cut -f9 -d' ' |
  while read subvolume; do
    echo "deleting /$subvolume subvolume..."
    btrfs subvolume delete "/mnt/$subvolume"
  done &&
  echo "deleting /root subvolume..." &&
  btrfs subvolume delete /mnt/root

  echo "restoring blank /root subvolume..."
  btrfs subvolume snapshot /mnt/root-blank /mnt/root

  # Once we're done rolling back to a blank snapshot,
  # we can unmount /mnt and continue on the boot process.
  umount /mnt
'';
#+END_SRC

** Copying Files to Persist
NixOS will take care of creating the specified symlinks, but we still need to
manually move relevant files we adding them to ~/persist~ for the first time,
i.e. after the previous steps run
#+BEGIN_SRC shell :tangle no 
sudo nixos-rebuild boot

# persist NetworkManager
sudo mkdir -p /persist/etc/NetworkManager
sudo cp -r {,/persist}/etc/NetworkManager/system-connections
sudo mkdir -p /persist/var/lib/NetworkManager
sudo cp /var/lib/NetworkManager/{secret_key,seen-bssids,timestamps} /persist/var/lib/NetworkManager/
# persist nixos
sudo cp -r {,/persist}/etc/nixos
sudo cp -r {,/persist}/etc/NIXOS
# persist adjtime
sudo cp {,/persist}/etc/adjtime
# copy bluetooth
sudo cp -r /var/lib/bluetooth /persist/var/lib/
#+END_SRC

* Home Manager
NixOS configurations aren't designed to generate user-specific configurations
(i.e. user installed packages or config files located in ~$HOME~. To do this we
need the [[https://rycee.gitlab.io/home-manager/][Home Manager]] add on
#+BEGIN_SRC nix :tangle no :noweb yes :noweb-ref insert-config-here
home-manager.users.dalvescb = { pkgs, config, ... }: {
  nixpkgs.config.allowUnfree = true;
  home.stateVersion = "20.09";
  home.packages = with pkgs; [
    gimp
    pavucontrol
    xorg.xmessage
    nitrogen
    font-awesome
    # font-awesome-ttf      # used by polybar
    material-design-icons # used by polybar
    xmonad-log
    pasystray
    blueman
    networkmanagerapplet
    networkmanager_dmenu
    dmenu
    # (pkgs.linkFarm "dmenu" [ {
    #   name = "bin/dmenu";
    #   path = "${pkgs.rofi}/bin/rofi";
    # } ])
    gnome.adwaita-icon-theme
    # dunst
    arc-icon-theme
    steam-run
    dconf2nix
    alacritty
  ];
  
  <<insert-home-here>>
  
};
#+END_SRC
*NOTE*: You need to import home-manager before using it (see [[#imports][Imports]]). All the
 following home-manager specific configurations are inserted into ~<<insert-home-here>>~

** Shell Configuration
I use zsh with a couple of non-standard plugins
which have to be fetched manually from GitHub, including:
  - [[https://github.com/zsh-users/zsh-autosuggestions][ZSH Autosuggestions]]
  - [[https://github.com/zsh-users/zsh-syntax-highlighting][ZSH Syntax Highlighting]]
    
#+BEGIN_SRC nix :tangle no :noweb-ref insert-home-here
programs.zsh.enable = true;
programs.zsh.oh-my-zsh.enable = true;
programs.zsh.oh-my-zsh.plugins = [ "git" ];
programs.zsh.oh-my-zsh.theme = "amuse";

programs.zsh.plugins = let
  zsh-syntax-highlighting = {
     name = "zsh-syntax-highlighting";
     src = pkgs.fetchFromGitHub {
       owner = "zsh-users";
       repo = "zsh-syntax-highlighting";
       rev = "0.7.1";
       sha256 = "03r6hpb5fy4yaakqm3lbf4xcvd408r44jgpv4lnzl9asp4sb9qc0";
     };
   };
  zsh-autosuggestions = {
     name = "zsh-autosuggestions";
     src = pkgs.fetchFromGitHub {
       owner = "zsh-users";
       repo = "zsh-autosuggestions";
       rev = "v0.6.4";
       sha256 = "0h52p2waggzfshvy1wvhj4hf06fmzd44bv6j18k3l9rcx6aixzn6";
     };
   };
  in [ 
      zsh-syntax-highlighting
      zsh-autosuggestions
     ];
#+END_SRC

*** Shell Aliases
Instead of in .profile, .bash, etc create aliases declaratively here 
#+BEGIN_SRC nix :tangle no :noweb-ref insert-config-here
programs.zsh.shellAliases = { 
  e = "emacsclient";
  ec ="emacsclient -c";
};
#+END_SRC

** Alacritty
Configuration of the Alacritty terminal emulator (see [[https://github.com/alacritty/alacritty/blob/master/alacritty.yml][Default Alacritty Config
File]] for configuration options)
#+BEGIN_SRC nix :tangle no :noweb-ref insert-home-here
programs.alacritty.enable = true;
programs.alacritty.settings = {
  window.opacity = 1.0;
  font.normal = {
    family = "Source Code Pro";
    style = "Regular";
  };
  font.bold = {
    family = "Source Code Pro";
    style = "Bold";
  };
  font.italic = {
    family = "Source Code Pro";
    style = "Italic";
  };
  font.bold_italic = {
    family = "Source Code Pro";
    style = "Bold Italic";
  };
  font.size = 14.0;
  import = [ "~/nixconfig/alacritty/dracula.yml" ];
  key_bindings = [
    {
      key = "N";
      mods = "Control|Shift";
      action = "SpawnNewInstance";
    }
  ];
};
#+END_SRC

** Nix-Direnv
A fast, persistent implementation of direnv's use-nix, see [[https://github.com/nix-community/nix-direnv][nix-direnv]] for
details
#+BEGIN_SRC nix :tangle no :noweb-ref insert-home-here
programs.direnv.enable = true;
programs.direnv.nix-direnv.enable = true;
#+END_SRC

** dconf Config (Gnome)
Dump current dconf settings with ~dconf dump / > dconf-backup~ 
#+BEGIN_SRC nix :tangle no :noweb-ref insert-home-here
# dconf.settings = {

#   "desktop/wm/keybindings" = { 
#       "close"= "['<Shift><Super>c']";
#       "cycle-windows"= "['<Super>o']";
#       "cycle-windows-backward"= "['<Shift><Super>o']";
#       "maximize"="@as []";
#       "minimize"="@as []";
#       "move-to-monitor-left"= "['<Shift><Super>j']";
#       "move-to-monitor-right"= "['<Shift><Super>k']";
#       "move-to-workspace-1"= "['<Shift><Super>exclam']";
#       "move-to-workspace-2"= "['<Shift><Super>at']";
#       "move-to-workspace-3"= "['<Shift><Super>numbersign']";
#       "move-to-workspace-4"= "['<Shift><Super>dollar']";
#       "move-to-workspace-left"= "['<Shift><Super>h']";
#       "move-to-workspace-right"= "['<Shift><Super>l']";
#       "switch-input-source"= "@as []";
#       "switch-input-source-backward"= "@as []";
#       "switch-to-workspace-1"= "['<Super>1']";
#       "switch-to-workspace-2"= "['<Super>2']";
#       "switch-to-workspace-3"= "['<Super>3']";
#       "switch-to-workspace-4"= "['<Super>4']";
#       "switch-to-workspace-left"= "['<Super>h']";
#       "switch-to-workspace-right"= "['<Super>l']";
#       "toggle-fullscreen"= "['<Shift><Super>space']";
#       "toggle-maximized"= "['<Super>i']";
#     };
  
#     "mutter/keybindings" = {
#       "switch-monitor" = "['XF86Display']";
#       "toggle-tiled-left" = "['<Super>j']";
#       "toggle-tiled-right" = "['<Super>k']";
#     };
  
#     "settings-daemon/plugins/media-keys" = {
#       "screensaver" = "@as []";
#       "search" = "['<Super>p']";
#     };
#   };
#+END_SRC

** XMonad + KDE #REMOVED
[[https://xmonad.org][XMonad]] is a tiling window manager written and configured in Haskell (which is a
good enough reason alone to make it the window manager for me)
#+BEGIN_SRC nix :tangle no
xsession = {
  enable = true;
  
  windowManager.xmonad = {
    enable = true;
    enableContribAndExtras = true;
    extraPackages = hp: [
      hp.dbus
      hp.monad-logger
      hp.xmonad-contrib
      hp.xmobar
    ];
    config = ./xmonad/xmonad.hs;
  };
};
#+END_SRC
In order to configure KDE to use xmonad as its window manager instead of its
default window manager (KWin), you need to configure the following script
(see [[https://wiki.haskell.org/Xmonad/Using_xmonad_in_KDE][wiki.haskell.org/Xmonad/Using_xmonad_in_KDE]] for details)
#+BEGIN_SRC nix :tangle no
home.file.".config/plasma-workspace/env/set_window_manager.sh".text = ''
                                                                    export KDEWM=${pkgs.haskellPackages.xmonad}/bin/xmonad
                                                                    '';
home.file.".config/plasma-workspace/env/set_window_manager.sh".executable = true;
#+END_SRC
** XMonad + None #REMOVED
[[https://xmonad.org][XMonad]] is a tiling window manager written and configured in Haskell (which is a
good enough reason alone to make it the window manager for me)
#+BEGIN_SRC nix :tangle no
xsession = let
  extraCommands = ''
      if [ $HOSTNAME = NixMachine ] ; then
                ${pkgs.xorg.xrandr}/bin/xrandr --output DP-0 --primary --mode 2560x1440 --panning 2560x1440+1440+678 --rate 144.00 --output DP-2 --mode 2560x1440 --panning 2560x1440+4000+927 --rate 144.00 --right-of DP-0 --output DP-4 --rotate right --mode 2560x1440 --rate 60.00 --left-of DP-0
      fi 
  '';
in {
  enable = true;
  
  initExtra = extraCommands;
  
  windowManager.xmonad = {
    enable = true;
    enableContribAndExtras = true;
    extraPackages = hp: [
      hp.dbus
      hp.monad-logger
      hp.xmonad-contrib
      hp.xmobar
    ];
    config = ./xmonad/xmonad.hs;
  };
};
#+END_SRC

** Picom #REMOVED
[[https://github.com/yshui/picom][Picom]] is a compositor. Wtf is a compositor?? Kind of a weird thing, according to
[[https://en.wikipedia.org/wiki/Compositing_window_manager][Wikipedia]] a compositing window manager is a provides applications with an
off-screen buffer for each window. In simpler terms, if you want fancy blurring
and other window effects you need one
#+BEGIN_SRC nix :tangle no
services.picom = {
    enable = true;
    # package = pkgs.picom.overrideAttrs(o: {
    #       src = pkgs.fetchFromGitHub {
    #         repo = "picom";
    #         owner = "ibhagwan";
    #         rev = "44b4970f70d6b23759a61a2b94d9bfb4351b41b1";
    #         sha256 = "0iff4bwpc00xbjad0m000midslgx12aihs33mdvfckr75r114ylh";
    #       };
    # });
    # activeOpacity = "1.0";
    # inactiveOpacity = "1.0";
    blur = true;
    backend = "glx";
    # experimentalBackends = true;
    fade = true;
    fadeDelta = 5;
    vSync = true;
    # opacityRule = [ 
    #                 "100:class_g   *?= 'Brave-browser'"
    #                 "60:class_g    *?= 'Alacritty'"
    #               ];
    
    shadow = true;
    shadowOpacity = "0.75";
    extraOptions = ''
                 xrender-sync-fence = true;
                 detect-client-opacity = true;
                 use-ewmh-active-win = true;
                 mark-ovredir-focused = false;
    '';
    #  mark-wmwin-focused = true;
    # inactive-opacity-override = true;
};
#+END_SRC

** GTK Theme #REMOVED
Even though gnome is not installed, you can still set the GTK theme for
any application that uses GTK
#+BEGIN_SRC nix :tangle no
gtk = {
  enable = true;
  iconTheme = {
    name = "Adwaita-dark";
    package = pkgs.gnome.adwaita-icon-theme;
  };
  theme = {
    name = "Adwaita-dark";
    package = pkgs.gnome.adwaita-icon-theme;
  };
};
#+END_SRC

** VS Code
This will enable VS Code using buildFHSUserEnv so that you can install
extensions without having to declare them in this config
#+BEGIN_SRC nix :tangle no :noweb-ref insert-home-here
programs.vscode.enable = true;
programs.vscode.package = pkgs.vscode-fhs;
#+END_SRC

** Keyboard Layout
This will set the keyboard layout (which used to be set by services.xserver)
#+BEGIN_SRC nix :tangle no :noweb-ref insert-home-here
home.keyboard = {
  layout = "us";
  options = [ "ctrl:swapcaps" ];
  };
#+END_SRC

** Rofi #REMOVED
[[https://github.com/davatorium/rofi][Rofi]] is an application launcher, which is nice to have when you don't have a
full desktop manager so you don't have to launch everything from terminal
#+BEGIN_SRC nix :tangle no 
programs.rofi = {
  enable = true;
  terminal = "${pkgs.alacritty}/bin/alacritty";
  theme = ./rofi/theme.rafi;
  # package = pkgs.rofi.override { plugins = [ pkgs.rofi-file-browser ]; };
};
#+END_SRC

** Polybar #REMOVED
XMonad doesn't come with any sort of dock/bar by default, [[https://github.com/polybar/polybar][Polybar]] is a highly
customizable status bar that integrates with many different desktop
environments
#+BEGIN_SRC nix :tangle no
services.polybar = let
  
  mypolybar = pkgs.polybar.override {
    alsaSupport = true;
    pulseSupport = true;
  };
  
  bluetoothScript = pkgs.callPackage ./polybar/bluetooth.nix {};
  bctl = ''
  [module/bctl]
  type = custom/script
  exec = ${bluetoothScript}/bin/bluetooth-ctl
  tail = true
  click-left = ${bluetoothScript}/bin/bluetooth-ctl --toggle &
  '';

  xmonad = ''
  [module/xmonad]
  type = custom/script
  exec = ${pkgs.xmonad-log}/bin/xmonad-log 

  tail = true
  '';

  primaryBar = ''
  [bar/primary]
  inherit = bar/main
  monitor = ''${env:MONITOR}
  modules-center = date
  modules-left   = ewmh
  tray-position  = right
  '';
  
  highDPIBar = ''
  [bar/highDPI]
  inherit = bar/main
  monitor = ''${env:MONITOR}
  modules-center = date
  modules-left   = ewmh
  modules-right  = battery backlight
  tray-position  = right
  dpi-x = 192
  dpi-y = 192
  tray-maxsize = 1000
  '';
  
in {
  enable = true;
  package = mypolybar;
  config = ./polybar/polybar.ini;
  extraConfig = xmonad + bctl + primaryBar + highDPIBar;
  script = ''
  if [ $HOSTNAME = "NixBot" ] ; then
    polybar highDPI 2>/home/dalvescb/.polybar_primary_error.log &
  else 
    polybar primary 2>/home/dalvescb/.polybar_primary_error.log &
  fi
  '';
};
#+END_SRC

** Dunst #REMOVED
[[https://dunst-project.org/][Dunst]] is a lightweight replacement for notification daemons provided by most
desktop environments. It's very customizable and isn't dependent on any toolkits
so fits into window manager centric setups (like XMonad with no Desktop Environment)
#+BEGIN_SRC nix :tangle no
services.dunst = {
  enable = true;
  iconTheme = {
    name = "Arc";
    # package = pkgs.gnome.adwaita-icon-theme;
    package = pkgs.arc-icon-theme;
    size = "16x16";
  };
  settings = {
    global = {
      monitor = 0;
      geometry = "500x50-50+65";
      shrink = "yes";
      transparency = 10;
      padding = 16;
      horizontal_padding = 16;
      font = "JetBrains Mono Medium 10";
      line_height = 4;
      format = ''<b>%s</b>\n%b'';
    };
  };
};
#+END_SRC

* FlySpell Local Words                                                    :ignore: :noexport:

#  LocalWords:  UEFI unfree NixOS OpenSSH BTRFS subvolume subvolumes WiFi GPU
#  LocalWords:  systemd's Nvidia VA API KDE mutably Bluetooth bluetooth distro
#  LocalWords:  TouchPad nixos FlySpell XMonad Polybar compositing GTK Rofi lib
#  LocalWords:  dmenu Dunst centric Dropbox nixpkgs Picom Xbox BetterLockscreen
#  LocalWords:  buildFHSUserEnv direnv direnv's NoiseTorch conf ertm KWin dconf
#  LocalWords:  xmonad TimeZone Systemd Config Alacritty Gamemode GameMode
#  LocalWords:  linux
