# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e86ce0d3-420e-484e-a59c-e0bdc9baa9a1";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/e5d72a76-a1af-460e-ab62-ce367a576d00";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e86ce0d3-420e-484e-a59c-e0bdc9baa9a1";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e86ce0d3-420e-484e-a59c-e0bdc9baa9a1";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/27C2-E970";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e86ce0d3-420e-484e-a59c-e0bdc9baa9a1";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/e86ce0d3-420e-484e-a59c-e0bdc9baa9a1";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b329eaca-b282-484b-b36a-5dce84af8168"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
